import type { WorkflowDefinition } from '../types';

export const OPS_WORKFLOW_DEFINITIONS: WorkflowDefinition[] = [
  {
    id: 'reuniones',
    name: 'Reuniones',
    description: 'Preparacion previa, procesamiento de notas/transcripciones y deteccion automatica.',
    summary: 'Unifica la preparacion, revision y sincronizacion de reuniones en un solo flujo.',
    engine: 'hybrid',
    triggerModes: ['activation', 'passive'],
    passiveBehavior: 'system',
    configurableFields: ['modo', 'fecha', 'equipo por defecto', 'proyecto por defecto', 'salida opcional a Chat'],
    requiredCapabilities: [],
    optionalCapabilities: ['calendar', 'drive', 'gmail', 'gchat', 'google_user_mapping'],
    defaultConfig: {
      mode: 'manual',
      targetDate: '',
      gchatSpace: '',
      meetingTitle: '',
      meetingType: 'general',
      defaultTeamId: '',
      defaultProjectId: '',
      manualText: '',
      driveRef: '',
    },
    modes: ['prep', 'manual', 'drive', 'auto'],
  },
  {
    id: 'drive',
    name: 'Drive',
    description: 'Crea espacios base de proyecto con plantillas de carpetas.',
    summary: 'Genera una estructura inicial y opcionalmente avisa al equipo.',
    engine: 'automation',
    triggerModes: ['activation'],
    configurableFields: ['nombre del proyecto', 'carpeta padre', 'plantilla de carpetas', 'salida opcional a Chat'],
    requiredCapabilities: ['drive'],
    optionalCapabilities: ['gchat'],
    defaultConfig: { projectName: '', parentFolderId: '', gchatSpace: '', folderPreset: 'cliente_estandar' },
  },
  {
    id: 'actualizacion_equipo',
    name: 'Actualizacion de equipo',
    description: 'Convierte contexto operativo en un mensaje ejecutivo para Google Chat.',
    summary: 'Redacta una actualizacion clara para un espacio de Chat.',
    engine: 'automation',
    triggerModes: ['activation'],
    configurableFields: ['destino', 'contexto', 'tono'],
    requiredCapabilities: ['gchat'],
    optionalCapabilities: [],
    defaultConfig: { spaceName: '', context: '', tone: 'ejecutivo y claro' },
  },
  {
    id: 'pc',
    name: 'PC',
    description: 'Prepara una accion operativa en la computadora con aprobacion obligatoria.',
    summary: 'Convierte un objetivo operativo en una tarea ejecutable por el agente de escritorio.',
    engine: 'automation',
    triggerModes: ['activation'],
    configurableFields: ['objetivo', 'backend preferido', 'URL inicial'],
    requiredCapabilities: [],
    optionalCapabilities: [],
    defaultConfig: { objective: '', backend: 'auto', startUrl: '' },
  },
];
