/**
 * Public facade for Gemini function-calling tool definitions.
 */
export {
  COMPUTER_TOOL_NAMES,
  COMPUTER_USE_TOOLS,
  GOOGLE_WORKSPACE_TOOL_NAMES,
  GOOGLE_WORKSPACE_TOOLS,
  INTEGRATED_BROWSER_TOOL_NAMES,
  INTEGRATED_BROWSER_TOOLS,
  NATIVE_AI_TOOL_NAMES,
  NATIVE_AI_TOOLS,
  PROJECT_HUB_TOOL_NAMES,
  PROJECT_HUB_TOOLS,
  WHATSAPP_SEND_FILE_TOOL,
} from './gemini-tools/index';
