/**
 * presentation-pdf.ts — Generate presentation slides as a beautiful PDF
 * using Electron's BrowserWindow + HTML/CSS for full design control.
 *
 * Each "page" of the PDF = one slide (landscape widescreen).
 * Uses CSS gradients, modern typography, flexbox layouts.
 * Images are generated by Gemini and embedded inline as base64.
 */

import { BrowserWindow } from 'electron';
import { GoogleGenerativeAI } from '@google/generative-ai';
import fs from 'node:fs/promises';

// ─────────────────────────────────────────────────────────────────────────────
// Types
// ─────────────────────────────────────────────────────────────────────────────
export interface SlideData {
  type: string;
  title: string;
  subtitle?: string;
  bullets?: string[];
  leftColumn?: { heading: string; items: string[] };
  rightColumn?: { heading: string; items: string[] };
  quote?: { text: string; author: string };
  imagePrompt?: string;
  notes?: string;
}

export interface ThemeConfig {
  colors?: {
    bg?: string;
    bgAlt?: string;
    accent?: string;
    accentAlt?: string;
    text?: string;
    textMuted?: string;
    heading?: string;
  };
  fontHeading?: string;
  fontBody?: string;
}

interface ResolvedColors {
  bg: string;
  bgAlt: string;
  accent: string;
  accentAlt: string;
  text: string;
  textMuted: string;
  heading: string;
}

interface ResolvedTheme {
  colors: ResolvedColors;
  fontHeading: string;
  fontBody: string;
}

// ─────────────────────────────────────────────────────────────────────────────
// Default theme
// ─────────────────────────────────────────────────────────────────────────────
const DEFAULTS: ResolvedColors = {
  bg: '0F1117', bgAlt: '1A1D2B', accent: '22D3EE', accentAlt: '6366F1',
  text: 'EAEAEA', textMuted: '9CA3AF', heading: 'FFFFFF',
};

function mergeTheme(custom?: ThemeConfig): ResolvedTheme {
  const cc = custom?.colors || {};
  return {
    colors: {
      bg: cc.bg || DEFAULTS.bg,
      bgAlt: cc.bgAlt || DEFAULTS.bgAlt,
      accent: cc.accent || DEFAULTS.accent,
      accentAlt: cc.accentAlt || DEFAULTS.accentAlt,
      text: cc.text || DEFAULTS.text,
      textMuted: cc.textMuted || DEFAULTS.textMuted,
      heading: cc.heading || DEFAULTS.heading,
    },
    fontHeading: custom?.fontHeading || 'Segoe UI',
    fontBody: custom?.fontBody || 'Segoe UI',
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Image Generation
// ─────────────────────────────────────────────────────────────────────────────
async function generateImage(genAI: GoogleGenerativeAI, prompt: string): Promise<string | null> {
  try {
    const imgModel = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-image' });
    const enhancedPrompt = `Generate a high-quality, professional photograph or illustration for a presentation slide. Style: modern, clean, corporate-quality. No text overlays, no watermarks. Subject: ${prompt}. Aspect ratio: 16:9 widescreen. Make it visually stunning.`;

    const result = await imgModel.generateContent({
      contents: [{ role: 'user', parts: [{ text: enhancedPrompt }] }],
      generationConfig: { responseModalities: ['IMAGE'] } as any,
    });

    const parts = result.response.candidates?.[0]?.content?.parts as any[] | undefined;
    if (parts) {
      for (const part of parts) {
        if (part.inlineData) {
          return `data:${part.inlineData.mimeType || 'image/png'};base64,${part.inlineData.data}`;
        }
      }
    }
    return null;
  } catch (err) {
    console.warn('[presentation-pdf] Image gen failed:', prompt, err);
    return null;
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// HTML Slide Renderers
// ─────────────────────────────────────────────────────────────────────────────
function h(hex: string): string { return `#${hex}`; }

function esc(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function renderSlide(slide: SlideData, th: ResolvedTheme, idx: number, total: number, img: string | null): string {
  const co = th.colors;
  const pb = idx > 0 ? 'page-break-before:always;' : '';

  const wrap = (inner: string, bg: string = h(co.bg)) =>
    `<div class="slide" style="${pb}background:${bg};position:relative;">${inner}<div class="sn">${idx + 1}/${total}</div>${slide.type !== 'title' && slide.type !== 'closing' ? '<div class="br">SofLIA</div>' : ''}</div>`;

  const imgBg = img ? `url('${img}') center/cover no-repeat` : '';
  const scrim = img ? `<div style="position:absolute;inset:0;background:linear-gradient(180deg,rgba(0,0,0,.3),rgba(0,0,0,.7));z-index:1"></div>` : '';
  const z = img ? 'position:relative;z-index:2;' : '';

  switch (slide.type) {
    case 'title':
      return wrap(`${scrim}
        <div class="ab" style="background:${h(co.accent)}"></div>
        <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;${z}">
          <div style="width:200px;height:3px;background:${h(co.accent)};margin-bottom:24px"></div>
          <h1 style="font-family:'${th.fontHeading}';font-size:48px;color:${h(co.heading)};text-align:center;margin:0;line-height:1.2;font-weight:700;text-shadow:0 2px 20px rgba(0,0,0,.3)">${esc(slide.title)}</h1>
          ${slide.subtitle ? `<p style="font-family:'${th.fontBody}';font-size:20px;color:${h(co.textMuted)};text-align:center;margin-top:20px">${esc(slide.subtitle)}</p>` : ''}
          <div style="width:200px;height:3px;background:${h(co.accent)};margin-top:30px"></div>
        </div>
        <div style="position:absolute;bottom:0;left:0;width:100%;height:8px;background:linear-gradient(90deg,${h(co.accent)},${h(co.accentAlt)});z-index:3"></div>
      `, img ? imgBg : `linear-gradient(135deg,${h(co.bg)},${h(co.bgAlt)})`);

    case 'section-break':
      return wrap(`${scrim}
        <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;${z}">
          <h1 style="font-family:'${th.fontHeading}';font-size:52px;color:${h(co.heading)};text-align:center;margin:0;font-weight:700;text-shadow:0 2px 20px rgba(0,0,0,.5)">${esc(slide.title)}</h1>
          ${slide.subtitle ? `<p style="font-family:'${th.fontBody}';font-size:20px;color:${h(co.textMuted)};text-align:center;margin-top:16px">${esc(slide.subtitle)}</p>` : ''}
        </div>
      `, img ? imgBg : h(co.accent));

    case 'content':
      return wrap(`
        <div class="ab" style="background:${h(co.accent)}"></div>
        <div style="display:flex;height:100%;gap:30px;padding:50px 50px 30px">
          <div style="flex:${img ? '.6' : '1'};display:flex;flex-direction:column">
            <h2 style="font-family:'${th.fontHeading}';font-size:32px;color:${h(co.accent)};margin:0 0 8px;font-weight:700">${esc(slide.title)}</h2>
            <div style="width:80px;height:3px;background:${h(co.accent)};margin-bottom:24px"></div>
            ${slide.bullets ? `<ul style="list-style:none;padding:0;margin:0">${slide.bullets.map(b => `<li style="font-family:'${th.fontBody}';font-size:17px;color:${h(co.text)};margin-bottom:14px;padding-left:20px;position:relative;line-height:1.5"><span style="position:absolute;left:0;color:${h(co.accent)};font-size:12px;top:5px">●</span>${esc(b.replace(/^[-•*]\s*/, ''))}</li>`).join('')}</ul>` : ''}
          </div>
          ${img ? `<div style="flex:.4;display:flex;align-items:center;justify-content:center"><img src="${img}" style="max-width:100%;max-height:90%;border-radius:12px;box-shadow:0 8px 32px rgba(0,0,0,.3);object-fit:cover"/></div>` : ''}
        </div>
      `, h(co.bg));

    case 'two-column':
      return wrap(`
        <div class="ab" style="background:${h(co.accent)}"></div>
        <div style="padding:50px 50px 30px;height:100%;display:flex;flex-direction:column">
          <h2 style="font-family:'${th.fontHeading}';font-size:32px;color:${h(co.accent)};margin:0 0 8px;font-weight:700">${esc(slide.title)}</h2>
          <div style="width:100%;height:2px;background:linear-gradient(90deg,${h(co.accent)}40,transparent);margin-bottom:24px"></div>
          <div style="display:flex;gap:30px;flex:1">
            <div style="flex:1;padding:20px;background:${h(co.bgAlt)};border-radius:12px">
              ${slide.leftColumn ? `<h3 style="font-family:'${th.fontHeading}';font-size:20px;color:${h(co.heading)};margin:0 0 16px;font-weight:600">${esc(slide.leftColumn.heading)}</h3><ul style="list-style:none;padding:0;margin:0">${slide.leftColumn.items.map(i => `<li style="font-family:'${th.fontBody}';font-size:15px;color:${h(co.text)};margin-bottom:10px;padding-left:18px;position:relative;line-height:1.4"><span style="position:absolute;left:0;color:${h(co.accent)}">●</span>${esc(i)}</li>`).join('')}</ul>` : ''}
            </div>
            <div style="width:2px;background:linear-gradient(180deg,${h(co.accent)}60,transparent)"></div>
            <div style="flex:1;padding:20px;background:${h(co.bgAlt)};border-radius:12px">
              ${slide.rightColumn ? `<h3 style="font-family:'${th.fontHeading}';font-size:20px;color:${h(co.heading)};margin:0 0 16px;font-weight:600">${esc(slide.rightColumn.heading)}</h3><ul style="list-style:none;padding:0;margin:0">${slide.rightColumn.items.map(i => `<li style="font-family:'${th.fontBody}';font-size:15px;color:${h(co.text)};margin-bottom:10px;padding-left:18px;position:relative;line-height:1.4"><span style="position:absolute;left:0;color:${h(co.accentAlt)}">●</span>${esc(i)}</li>`).join('')}</ul>` : ''}
            </div>
          </div>
        </div>
      `, h(co.bg));

    case 'image-focus':
      return wrap(`${scrim}
        <div style="position:absolute;bottom:40px;left:50px;right:50px;${z}">
          <h2 style="font-family:'${th.fontHeading}';font-size:36px;color:${h(co.heading)};margin:0;font-weight:700;text-shadow:0 2px 12px rgba(0,0,0,.5)">${esc(slide.title)}</h2>
          ${slide.subtitle ? `<p style="font-family:'${th.fontBody}';font-size:16px;color:${h(co.textMuted)};margin-top:8px">${esc(slide.subtitle)}</p>` : ''}
        </div>
        <div style="position:absolute;bottom:0;left:0;width:100%;height:4px;background:${h(co.accent)};z-index:3"></div>
      `, img ? imgBg : h(co.bgAlt));

    case 'quote': {
      const qt = slide.quote?.text || slide.bullets?.[0] || slide.title;
      const qa = slide.quote?.author || slide.subtitle || '';
      return wrap(`
        <div class="ab" style="background:${h(co.accent)}"></div>
        <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;padding:60px">
          <span style="font-size:100px;color:${h(co.accent)};opacity:.3;font-family:Georgia;line-height:.8;margin-bottom:10px">"</span>
          <p style="font-family:Georgia;font-size:26px;color:${h(co.text)};text-align:center;font-style:italic;line-height:1.6;max-width:800px;margin:0">${esc(qt)}</p>
          ${qa ? `<div style="width:80px;height:2px;background:${h(co.accent)};margin:24px 0 16px"></div><p style="font-family:'${th.fontBody}';font-size:16px;color:${h(co.textMuted)};text-align:center;margin:0">— ${esc(qa)}</p>` : ''}
        </div>
      `, h(co.bgAlt));
    }

    case 'comparison':
      return wrap(`
        <div class="ab" style="background:${h(co.accent)}"></div>
        <div style="padding:50px 50px 30px;height:100%;display:flex;flex-direction:column">
          <h2 style="font-family:'${th.fontHeading}';font-size:32px;color:${h(co.accent)};margin:0 0 24px;font-weight:700">${esc(slide.title)}</h2>
          <div style="display:flex;gap:20px;flex:1;position:relative">
            <div style="flex:1;padding:24px;background:${h(co.bgAlt)};border-radius:12px">
              ${slide.leftColumn ? `<h3 style="font-family:'${th.fontHeading}';font-size:20px;color:${h(co.accent)};margin:0 0 16px;text-align:center;font-weight:600">${esc(slide.leftColumn.heading)}</h3><ul style="list-style:none;padding:0">${slide.leftColumn.items.map(i => `<li style="font-family:'${th.fontBody}';font-size:14px;color:${h(co.text)};margin-bottom:8px;padding-left:18px;position:relative"><span style="position:absolute;left:0;color:${h(co.accent)}">✓</span>${esc(i)}</li>`).join('')}</ul>` : ''}
            </div>
            <div style="position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);width:50px;height:50px;background:${h(co.accent)};border-radius:50%;display:flex;align-items:center;justify-content:center;z-index:2">
              <span style="font-family:'${th.fontHeading}';font-size:14px;color:${h(co.bg)};font-weight:700">VS</span>
            </div>
            <div style="flex:1;padding:24px;background:${h(co.bgAlt)};border-radius:12px">
              ${slide.rightColumn ? `<h3 style="font-family:'${th.fontHeading}';font-size:20px;color:${h(co.accentAlt)};margin:0 0 16px;text-align:center;font-weight:600">${esc(slide.rightColumn.heading)}</h3><ul style="list-style:none;padding:0">${slide.rightColumn.items.map(i => `<li style="font-family:'${th.fontBody}';font-size:14px;color:${h(co.text)};margin-bottom:8px;padding-left:18px;position:relative"><span style="position:absolute;left:0;color:${h(co.accentAlt)}">✓</span>${esc(i)}</li>`).join('')}</ul>` : ''}
            </div>
          </div>
        </div>
      `, h(co.bg));

    case 'closing':
      return wrap(`${scrim}
        <div style="position:absolute;top:0;left:0;width:100%;height:4px;background:linear-gradient(90deg,${h(co.accent)},${h(co.accentAlt)});z-index:3"></div>
        <div style="display:flex;flex-direction:column;align-items:center;justify-content:center;height:100%;${z}">
          <h1 style="font-family:'${th.fontHeading}';font-size:52px;color:${h(co.heading)};text-align:center;margin:0;font-weight:700;text-shadow:0 2px 20px rgba(0,0,0,.3)">${esc(slide.title || '¡Gracias!')}</h1>
          ${slide.subtitle ? `<p style="font-family:'${th.fontBody}';font-size:18px;color:${h(co.textMuted)};text-align:center;margin-top:20px">${esc(slide.subtitle)}</p>` : ''}
          <div style="width:120px;height:3px;background:${h(co.accent)};margin-top:30px"></div>
        </div>
        <div style="position:absolute;bottom:0;left:0;width:100%;height:4px;background:linear-gradient(90deg,${h(co.accent)},${h(co.accentAlt)});z-index:3"></div>
      `, img ? imgBg : `linear-gradient(135deg,${h(co.bg)},${h(co.bgAlt)})`);

    default:
      return renderSlide({ ...slide, type: 'content' }, th, idx, total, img);
  }
}

// ─────────────────────────────────────────────────────────────────────────────
// Full HTML document
// ─────────────────────────────────────────────────────────────────────────────
function buildHTML(slides: string[], th: ResolvedTheme): string {
  return `<!DOCTYPE html><html><head><meta charset="UTF-8"><style>
@page{size:landscape;margin:0}*{box-sizing:border-box}body{margin:0;padding:0}
.slide{width:1280px;height:720px;overflow:hidden;position:relative}
.ab{position:absolute;top:0;left:0;width:100%;height:4px;z-index:10}
.sn{position:absolute;bottom:12px;right:20px;font-family:'${th.fontBody}';font-size:11px;color:#${th.colors.textMuted};z-index:10}
.br{position:absolute;bottom:12px;left:20px;font-family:'${th.fontBody}';font-size:10px;color:#${th.colors.textMuted};font-style:italic;z-index:10}
</style></head><body>${slides.join('')}</body></html>`;
}

// ─────────────────────────────────────────────────────────────────────────────
// Fallback: Parse raw markdown into SlideData[]
// ─────────────────────────────────────────────────────────────────────────────
export function parseMarkdownToSlides(content: string, title: string): SlideData[] {
  const slides: SlideData[] = [];
  const lines = content.split('\n');
  let curTitle = '';
  let curBullets: string[] = [];
  let isFirst = true;

  const flush = () => {
    if (!curTitle && curBullets.length === 0) return;
    if (isFirst) {
      slides.push({ type: 'title', title: curTitle || title, subtitle: curBullets.length > 0 ? curBullets.join(' • ') : undefined, imagePrompt: `Professional abstract visual representing: ${curTitle || title}` });
      isFirst = false;
    } else {
      const types = ['content', 'content', 'image-focus', 'content'];
      slides.push({ type: types[slides.length % 4], title: curTitle, bullets: curBullets.length > 0 ? curBullets : undefined, imagePrompt: `Professional visual about: ${curTitle}` });
    }
    curTitle = '';
    curBullets = [];
  };

  for (const line of lines) {
    const t = line.trim();
    if (t.startsWith('## ') || t.startsWith('# ')) { flush(); curTitle = t.replace(/^#{1,3}\s*/, ''); }
    else if (t !== '') { curBullets.push(t.replace(/^[-•*]\s*/, '')); }
  }
  flush();

  if (slides.length > 0) {
    slides.push({ type: 'closing', title: '¡Gracias!', subtitle: 'Presentación generada por SofLIA', imagePrompt: 'Professional thank you slide background, abstract gradient' });
  }
  return slides;
}

// ─────────────────────────────────────────────────────────────────────────────
// Public API
// ─────────────────────────────────────────────────────────────────────────────
export interface CreatePresentationPDFOptions {
  slides: SlideData[];
  title: string;
  outputPath: string;
  customTheme?: ThemeConfig;
  includeImages?: boolean;
  genAI?: GoogleGenerativeAI;
}

export async function createPresentationPDF(options: CreatePresentationPDFOptions): Promise<string> {
  const { slides, title, outputPath, customTheme, includeImages = true, genAI } = options;
  const theme = mergeTheme(customTheme);

  console.log(`[presentation-pdf] Building ${slides.length} slides, images=${includeImages}`);

  // Generate images in parallel (batch of 3)
  const imageCache = new Map<number, string | null>();
  if (includeImages && genAI) {
    const BATCH = 3;
    for (let i = 0; i < slides.length; i += BATCH) {
      const batch = slides.slice(i, i + BATCH);
      const results = await Promise.allSettled(
        batch.map(s => s.imagePrompt ? generateImage(genAI, s.imagePrompt) : Promise.resolve(null)),
      );
      results.forEach((r, idx) => {
        imageCache.set(i + idx, r.status === 'fulfilled' ? r.value : null);
      });
    }
    console.log(`[presentation-pdf] Images: ${Array.from(imageCache.values()).filter(Boolean).length}/${slides.length}`);
  }

  // Render all slides to HTML
  const slideHTMLs = slides.map((s, i) => renderSlide(s, theme, i, slides.length, imageCache.get(i) || null));
  const fullHTML = buildHTML(slideHTMLs, theme);

  // Render to PDF using Electron BrowserWindow
  const win = new BrowserWindow({ show: false, width: 1280, height: 720, webPreferences: { offscreen: true } });

  try {
    await new Promise<void>((resolve, reject) => {
      win.webContents.on('did-finish-load', async () => {
        try {
          await new Promise(r => setTimeout(r, 1500)); // wait for images to load
          const pdfData = await win.webContents.printToPDF({
            printBackground: true,
            landscape: true,
            pageSize: { width: 338667, height: 190500 }, // ~13.33 x 7.5 inches in microns
            margins: { top: 0, bottom: 0, left: 0, right: 0 },
          });
          await fs.writeFile(outputPath, pdfData);
          resolve();
        } catch (e) { reject(e); }
      });
      win.loadURL(`data:text/html;charset=utf-8,${encodeURIComponent(fullHTML)}`);
    });
  } finally {
    win.destroy();
  }

  console.log(`[presentation-pdf] Saved: ${outputPath} (${slides.length} slides)`);
  return outputPath;
}
