export const CHANNEL_GROUP_4 = [
  'memory:search',
  'meeting:list-runs',
  'meeting:get-run-detail',
  'meeting:create-manual-run',
  'meeting:create-drive-run',
  'meeting:approve-asset',
  'meeting:approve-actions',
  'meeting:update-action',
  'meeting:reject-action',
  'meeting:sync-approved-actions',
  'meeting:get-followups',
  'meeting:get-context',
  'meeting:detected',
  'flow-send-to-chat',
  'flow:insert-text',
  'close-flow',
  'flow-message-received',
  'flow-window-shown',
  'updater:check-for-updates',
  'updater:download-update',
  'updater:install-update',
  'updater:get-status',
  'updater:update-available',
  'updater:download-progress',
  'updater:update-downloaded',
  'updater:error',
] as const;
