import type { PreloadBridge, SafeIpc } from './types';
import type { BrowserSyncControlRequest } from '../integrated-browser/platform-types';

export function exposeIntegratedBrowserApi(bridge: PreloadBridge, ipc: SafeIpc): void {
  const { safeInvoke, safeOn } = ipc;
  bridge.exposeInMainWorld('integratedBrowser', {
    getState: () => safeInvoke('integrated-browser:get-state'),
    getRuntimeDiagnostic: () => safeInvoke('integrated-browser:runtime-diagnostic'),
    getSyncDevices: () => safeInvoke('integrated-browser:sync-devices-get'),
    registerSyncDevice: () => safeInvoke('integrated-browser:sync-devices-register'),
    revokeSyncDevice: (id: string) => safeInvoke('integrated-browser:sync-devices-revoke', { id }),
    cancelSyncOperation: () => safeInvoke('integrated-browser:sync-devices-cancel'),
    controlSync: (input: BrowserSyncControlRequest) => safeInvoke('integrated-browser:sync-control', input),
    exportRuntimeDiagnostic: () => safeInvoke('integrated-browser:runtime-diagnostic-export'),
    restorePreviousSession: () => safeInvoke('integrated-browser:session-restore'),
    discardPreviousSession: () => safeInvoke('integrated-browser:session-discard'),
    captureVisible: () => safeInvoke('integrated-browser:capture-visible'),
    getObservation: (forceFresh = false) => safeInvoke('integrated-browser:get-observation', { forceFresh }),
    setObservationEnabled: (enabled: boolean) => safeInvoke('integrated-browser:set-observation-enabled', { enabled }),
    open: (url?: string) => safeInvoke('integrated-browser:open', url === undefined ? {} : { url }),
    navigate: (target: string) => safeInvoke('integrated-browser:navigate', { target }),
    findInPage: (query: string, forward = true) => safeInvoke('integrated-browser:page-find', { query, forward }),
    stopFindInPage: () => safeInvoke('integrated-browser:page-find-stop'),
    setZoom: (action: 'in' | 'out' | 'reset') => safeInvoke('integrated-browser:page-zoom', { action }),
    setMuted: (muted: boolean) => safeInvoke('integrated-browser:page-mute', { muted }),
    toggleFullscreen: () => safeInvoke('integrated-browser:page-fullscreen'),
    printPage: () => safeInvoke('integrated-browser:page-print'),
    savePageAsPdf: () => safeInvoke('integrated-browser:page-save-pdf'),
    listDownloads: () => safeInvoke('integrated-browser:downloads-list'),
    cancelDownload: (id: string) => safeInvoke('integrated-browser:downloads-cancel', { id }),
    resumeDownload: (id: string) => safeInvoke('integrated-browser:downloads-resume', { id }),
    retryDownload: (id: string) => safeInvoke('integrated-browser:downloads-retry', { id }),
    openDownload: (id: string) => safeInvoke('integrated-browser:downloads-open', { id }),
    revealDownload: (id: string) => safeInvoke('integrated-browser:downloads-reveal', { id }),
    clickElement: (ref: string) => safeInvoke('integrated-browser:element-click', { ref }),
    typeInElement: (ref: string, text: string, submit = false) =>
      safeInvoke('integrated-browser:element-type', { ref, text, submit }),
    scrollView: (direction: 'up' | 'down' | 'left' | 'right', amount?: number) =>
      safeInvoke('integrated-browser:scroll', { direction, amount }),
    createTab: (url?: string) => safeInvoke('integrated-browser:tab-create', url === undefined ? {} : { url }),
    closeTab: (tabId: string) => safeInvoke('integrated-browser:tab-close', { tabId }),
    duplicateTab: (tabId: string) => safeInvoke('integrated-browser:tab-duplicate', { tabId }),
    reopenClosedTab: (tabId?: string) => tabId === undefined ? safeInvoke('integrated-browser:tab-reopen-closed') : safeInvoke('integrated-browser:tab-reopen-closed', { tabId }),
    listRecentlyClosedTabs: () => safeInvoke('integrated-browser:tabs-recently-closed'),
    getHistoryRetention: () => safeInvoke('integrated-browser:history-retention-get'),
    setHistoryRetention: (days: number | null) => safeInvoke('integrated-browser:history-retention-set', { days }),
    closeOtherTabs: (tabId: string) => safeInvoke('integrated-browser:tab-close-others', { tabId }),
    closeTabsToRight: (tabId: string) => safeInvoke('integrated-browser:tab-close-right', { tabId }),
    setTabPinned: (tabId: string, pinned: boolean) => safeInvoke('integrated-browser:tab-pin', { tabId, pinned }),
    setTabLayout: (layout: 'horizontal' | 'vertical') => safeInvoke('integrated-browser:tab-layout', { layout }),
    createTabGroup: (name: string, color: string) => safeInvoke('integrated-browser:tab-group-create', { name, color }),
    assignTabGroup: (tabId: string, groupId: string | null) => safeInvoke('integrated-browser:tab-group-assign', { tabId, groupId }),
    activateTab: (tabId: string) => safeInvoke('integrated-browser:tab-activate', { tabId }),
    detachTab: (tabId: string) => safeInvoke('integrated-browser:tab-detach', { tabId }),
    reattachTab: (tabId: string) => safeInvoke('integrated-browser:tab-reattach', { tabId }),
    reorderTabs: (sourceId: string, targetId: string) => safeInvoke('integrated-browser:tab-reorder', { sourceId, targetId }),
    setViewMode: (mode: 'single' | 'split' | 'overlay', secondaryTabId?: string) =>
      safeInvoke('integrated-browser:view-mode', { mode, secondaryTabId }),
    goBack: () => safeInvoke('integrated-browser:go-back'),
    goForward: () => safeInvoke('integrated-browser:go-forward'),
    reload: () => safeInvoke('integrated-browser:reload'),
    stop: () => safeInvoke('integrated-browser:stop'),
    focus: () => safeInvoke('integrated-browser:focus'),
    toggleDevTools: () => safeInvoke('integrated-browser:toggle-devtools'),
    setViewport: (viewport: { x: number; y: number; width: number; height: number }) =>
      safeInvoke('integrated-browser:set-viewport', viewport),
    setOverlayBounds: (bounds: { x: number; y: number; width: number; height: number }) =>
      safeInvoke('integrated-browser:set-overlay-bounds', bounds),
    setOverlayPosition: (pos: string) =>
      safeInvoke('integrated-browser:set-overlay-position', { pos }),
    hide: () => safeInvoke('integrated-browser:hide'),
    readActiveDocument: () => safeInvoke('integrated-browser:document-read'),
    prepareReadingMode: (input?: { sourceUrl?: string; selection?: string }) => safeInvoke('integrated-browser:reading-prepare', input ?? {}),
    synthesizeReadingSegment: (input: { readingId: string; requestId: string; start: number; end: number }) => safeInvoke('integrated-browser:reading-synthesize', input),
    highlightReadingRange: (input: { readingId: string; start?: number; end?: number }) => safeInvoke('integrated-browser:reading-highlight', input),
    waitForReadingToolbarAction: (input: { readingId: string }) => safeInvoke('integrated-browser:reading-toolbar-wait', input),
    syncReadingToolbar: (input: { readingId: string; status: 'idle' | 'loading' | 'playing' | 'paused' | 'completed' | 'error'; speed: number; message?: string }) => safeInvoke('integrated-browser:reading-toolbar-sync', input),
    cancelReadingSpeech: (input: { readingId: string; requestId?: string }) => safeInvoke('integrated-browser:reading-cancel', input),
    closeReadingMode: (input: { readingId: string }) => safeInvoke('integrated-browser:reading-close', input),
    listHistory: (query?: string, limit?: number, filters?: { offset?: number; from?: string; to?: string; domain?: string }) => safeInvoke('integrated-browser:history-list', { query, limit, ...filters }),
    importHistory: () => safeInvoke('integrated-browser:history-import'),
    getProfile: () => safeInvoke('integrated-browser:profile-get'),
    setProfile: (kind: 'authenticated' | 'guest' | 'private') => safeInvoke('integrated-browser:profile-set', { kind }),
    listBookmarks: (query?: string) => safeInvoke('integrated-browser:bookmarks-list', { query }),
    saveBookmark: (input: { id?: string; url: string; title: string; folderId?: string | null; tags?: string[]; position?: number }) => safeInvoke('integrated-browser:bookmarks-save', input),
    removeBookmark: (id: string) => safeInvoke('integrated-browser:bookmarks-remove', { id }),
    migrateLegacyBookmarks: (entries: unknown[]) => safeInvoke('integrated-browser:bookmarks-migrate', { entries }),
    importBookmarksHtml: () => safeInvoke('integrated-browser:bookmarks-import-html'),
    exportBookmarksHtml: () => safeInvoke('integrated-browser:bookmarks-export-html'),
    recoverBookmarks: () => safeInvoke('integrated-browser:bookmarks-recover'),
    recoverPolicyStore: (input: unknown) => safeInvoke('integrated-browser:policy-recover', input),
    getAgentPolicy: (origin?: string) => safeInvoke('integrated-browser:agent-policy-get', { origin }),
    agentAudit: (input: unknown) => safeInvoke('integrated-browser:agent-audit', input),
    agentShortcuts: (input: unknown) => safeInvoke('integrated-browser:agent-shortcuts', input),
    semanticMemoryCommand: (input: unknown) => safeInvoke('integrated-browser:semantic-memory', input),
    credentialSessionCommand: (input: unknown) => safeInvoke('integrated-browser:credential-session', input),
    controlAgentTask: (input: unknown) => safeInvoke('integrated-browser:agent-control', input),
    setAgentPolicy: (input: { origin?: string; mode: 'strict' | 'balanced'; decision: 'ask' | 'allow-always' | 'block' }) => safeInvoke('integrated-browser:agent-policy-set', input),
    decideAgentPolicy: (input: { id: string; decision: 'allow-once' | 'allow-always' | 'block' }) => safeInvoke('integrated-browser:agent-policy-decide', input),
    getPrivacySite: (origin?: string) => safeInvoke('integrated-browser:privacy-site-get', { origin }),
    setPrivacySite: (input: { origin?: string; level: 'off' | 'balanced' | 'strict'; exceptionCategories: string[] }) => safeInvoke('integrated-browser:privacy-site-set', input),
    clearHistory: () => safeInvoke('integrated-browser:history-clear'),
    clearBrowsingData: (input: { categories: string[]; range: string }) =>
      safeInvoke('integrated-browser:clear-browsing-data', input),
    listCredentials: () => safeInvoke('integrated-browser:credentials-list'),
    setCredentialAutosave: (enabled: boolean) => safeInvoke('integrated-browser:credentials-autosave-set', { enabled }),
    analyzeCredentialHealth: () => safeInvoke('integrated-browser:credentials-health'),
    importCredentials: () => safeInvoke('integrated-browser:credentials-import'),
    exportCredentials: () => safeInvoke('integrated-browser:credentials-export'),
    recoverCredentials: () => safeInvoke('integrated-browser:credentials-recover'),
    saveCredential: (input: { id?: string; username: string; password: string; expectedOrigin: string }) => safeInvoke('integrated-browser:credentials-save', input),
    fillCredential: (id: string) => safeInvoke('integrated-browser:credentials-fill', { id }),
    removeCredential: (id: string) => safeInvoke('integrated-browser:credentials-remove', { id }),
    listExtensions: () => safeInvoke('integrated-browser:extensions-list'),
    extensionCatalog: (input: unknown) => safeInvoke('integrated-browser:extensions-catalog', input),
    installExtension: () => safeInvoke('integrated-browser:extensions-install'),
    confirmExtensionInstall: (token: string) => safeInvoke('integrated-browser:extensions-confirm-install', { token }),
    setExtensionEnabled: (installId: string, enabled: boolean) => safeInvoke('integrated-browser:extensions-set-enabled', { installId, enabled }),
    restrictExtensionSites: (installId: string, sites: string[]) => safeInvoke('integrated-browser:extensions-restrict-sites', { installId, sites }),
    removeExtension: (installId: string) => safeInvoke('integrated-browser:extensions-remove', { installId }),
    getSitePermissions: () => safeInvoke('integrated-browser:site-permissions-get'),
    setSitePermission: (input: { origin?: string; kind: string; state: 'ask' | 'granted' | 'denied' }) =>
      safeInvoke('integrated-browser:site-permissions-set', input),
    resetSitePermissions: (input?: { origin?: string }) =>
      safeInvoke('integrated-browser:site-permissions-reset', input ?? {}),
    getTabSummaries: () => safeInvoke('integrated-browser:tab-summaries'),
    getTabContent: (tabId: string, expected?: import('../../src/shared/browser-tab-context').BrowserTabExpectation) => safeInvoke('integrated-browser:get-tab-content', expected ? { tabId, expected } : { tabId }),
    onStateChanged: (callback: (state: unknown) => void) => safeOn('integrated-browser:state-changed', callback),
    onDownloadsChanged: (callback: (downloads: unknown) => void) => safeOn('integrated-browser:downloads-changed', callback),
    onFindRequested: (callback: () => void) => safeOn('integrated-browser:find-requested', callback),
    onOpenRequested: (callback: (request: unknown) => void) => safeOn('integrated-browser:open-requested', callback),
    onSelectionAction: (callback: (request: unknown) => void) => safeOn('integrated-browser:selection-action', callback),
    onReadingModeRequested: (callback: (request: unknown) => void) => safeOn('integrated-browser:reading-mode-requested', callback),
    onWritingRequest: (callback: (request: unknown) => void) => safeOn('integrated-browser:writing-request', callback),
    resolveWriting: (input: { requestId: string; text?: string; error?: string }) =>
      safeInvoke('integrated-browser:writing-resolve', input),
    onSitePermissionsChanged: (callback: (payload: unknown) => void) => safeOn('integrated-browser:site-permissions-changed', callback),
    decidePermissionPrompt: (input: { id: string; granted: boolean }) =>
      safeInvoke('integrated-browser:permission-decide', input),
    onPermissionPrompt: (callback: (request: unknown) => void) => safeOn('integrated-browser:permission-prompt', callback),
    onAgentPolicyPrompt: (callback: (request: unknown) => void) => safeOn('integrated-browser:agent-policy-prompt', callback),
  });
}
