import { init } from './meeting-store/init';
import { findRunByOwnerAndSourceHash } from './meeting-store/find-run-by-owner-and-source-hash';
import { createRun } from './meeting-store/create-run';
import { getNextSourceVersion } from './meeting-store/get-next-source-version';
import { addSourceArtifact } from './meeting-store/add-source-artifact';
import { addAsset } from './meeting-store/add-asset';
import { replaceSyncActions } from './meeting-store/replace-sync-actions';
import { listRuns } from './meeting-store/list-runs';
import { getRunDetail } from './meeting-store/get-run-detail';
import { updateRunStatus } from './meeting-store/update-run-status';
import { updateRunClassification } from './meeting-store/update-run-classification';
import { approveAsset } from './meeting-store/approve-asset';
import { approveActions } from './meeting-store/approve-actions';
import { rejectAction } from './meeting-store/reject-action';
import { updateActionDraft } from './meeting-store/update-action-draft';
import { getAction } from './meeting-store/get-action';
import { getApprovedPendingActions } from './meeting-store/get-approved-pending-actions';
import { updateActionSyncState } from './meeting-store/update-action-sync-state';
import { getFollowups } from './meeting-store/get-followups';
import { recordApproval } from './meeting-store/record-approval';
import { countActions } from './meeting-store/count-actions';
import { mapRun } from './meeting-store/map-run';
import { mapSourceArtifact } from './meeting-store/map-source-artifact';
import { mapAsset } from './meeting-store/map-asset';
import { mapSyncAction } from './meeting-store/map-sync-action';
import { mapApproval } from './meeting-store/map-approval';

export class MeetingStore {
  init = init;
  findRunByOwnerAndSourceHash = findRunByOwnerAndSourceHash;
  createRun = createRun;
  getNextSourceVersion = getNextSourceVersion;
  addSourceArtifact = addSourceArtifact;
  addAsset = addAsset;
  replaceSyncActions = replaceSyncActions;
  listRuns = listRuns;
  getRunDetail = getRunDetail;
  updateRunStatus = updateRunStatus;
  updateRunClassification = updateRunClassification;
  approveAsset = approveAsset;
  approveActions = approveActions;
  rejectAction = rejectAction;
  updateActionDraft = updateActionDraft;
  getAction = getAction;
  getApprovedPendingActions = getApprovedPendingActions;
  updateActionSyncState = updateActionSyncState;
  getFollowups = getFollowups;
  recordApproval = recordApproval;
  countActions = countActions;
  mapRun = mapRun;
  mapSourceArtifact = mapSourceArtifact;
  mapAsset = mapAsset;
  mapSyncAction = mapSyncAction;
  mapApproval = mapApproval;
}
