import { vi } from 'vitest';
import { DEFAULT_CONFIG } from '../desktop-agent-types';

export const expectedDesktopAgentChannels = [
  'desktop-agent:execute-task',
  'desktop-agent:execute-parallel',
  'desktop-agent:get-active-tasks',
  'desktop-agent:abort-task',
  'desktop-agent:abort',
  'desktop-agent:get-status',
  'desktop-agent:get-config',
  'desktop-agent:list-browser-profiles',
  'desktop-agent:reset-browser-profile',
  'desktop-agent:set-config',
  'desktop-agent:start-observation',
  'desktop-agent:stop-observation',
  'desktop-agent:click',
  'desktop-agent:double-click',
  'desktop-agent:right-click',
  'desktop-agent:drag',
  'desktop-agent:type',
  'desktop-agent:key',
  'desktop-agent:scroll',
  'desktop-agent:focus-window',
  'desktop-agent:list-windows',
  'desktop-agent:take-screenshot',
];

export function createMockDesktopAgentService() {
  return {
    executeTask: vi.fn(async () => 'Task completed'),
    executeParallelTasks: vi.fn(async () => []),
    getActiveTasks: vi.fn(() => []),
    abort: vi.fn(),
    abortAll: vi.fn(),
    getStatus: vi.fn(() => ({
      status: 'idle',
      currentTask: null,
      currentStep: 0,
      maxSteps: 200,
      plan: null,
      lastAction: null,
      config: DEFAULT_CONFIG,
      activeTasks: [],
      totalActiveAgents: 0,
    })),
    getConfig: vi.fn(() => ({ ...DEFAULT_CONFIG })),
    setConfig: vi.fn(),
    startObservation: vi.fn(async () => {}),
    stopObservation: vi.fn(),
    mouseClick: vi.fn(async () => {}),
    mouseDoubleClick: vi.fn(async () => {}),
    mouseRightClick: vi.fn(async () => {}),
    mouseDrag: vi.fn(async () => {}),
    keyboardType: vi.fn(async () => {}),
    keyboardKey: vi.fn(async () => {}),
    mouseScroll: vi.fn(async () => {}),
    focusWindow: vi.fn(async () => true),
    listWindows: vi.fn(async () => []),
    takeScreenshot: vi.fn(async () => 'base64data'),
    listBrowserProfiles: vi.fn(() => []),
    resetBrowserProfile: vi.fn(async () => ({ success: true })),
  };
}
