import type { MeetingRunDetail } from '../meetings/meeting-types';

export function createRunDetailFixture(): MeetingRunDetail {
  return {
    run: {
      id: 'mrun_test_123',
      organization_id: null,
      workspace_id: null,
      owner_user_id: '5551234567',
      origin_channel: 'system',
      origin_ref: 'drive:test',
      meeting_title: 'Weekly Delivery Sync',
      meeting_type: 'delivery_weekly_sync',
      meeting_series_key: null,
      primary_source_uri: null,
      status: 'REVIEW_REQUIRED',
      source_hash: 'hash',
      source_version: 1,
      trace_id: 'trace-1',
      last_error: null,
      created_at: '2026-03-25T10:00:00.000Z',
      updated_at: '2026-03-25T10:05:00.000Z',
    },
    source_artifacts: [],
    latest_asset: {
      id: 'asset-1',
      meeting_run_id: 'mrun_test_123',
      schema_version: 'meeting_asset.v1',
      asset_version: 1,
      executive_summary: 'Se revisaron avances del sprint, bloqueos de QA y acuerdos para cerrar pendientes hoy.',
      operational_summary: 'Seguimiento semanal con foco en entrega y riesgos.',
      review_flags: [],
      confidence: 0.88,
      created_at: '2026-03-25T10:05:00.000Z',
      payload: {
        schema_version: 'meeting_asset.v1',
        meeting_run_id: 'mrun_test_123',
        trace_id: 'trace-1',
        meeting_title: 'Weekly Delivery Sync',
        meeting_type: 'delivery_weekly_sync',
        source_refs: [],
        participants: [],
        decisions: [],
        commitments: [],
        issues: [],
        open_questions: [],
        parking_lot: [],
        executive_summary: 'Se revisaron avances del sprint, bloqueos de QA y acuerdos para cerrar pendientes hoy.',
        operational_summary: 'Seguimiento semanal con foco en entrega y riesgos.',
        review_flags: [],
        proposed_actions: [],
        continuity_context: [],
        analysis_result: {
          meetingType: { suggestedType: 'delivery_weekly_sync', alternativeTypes: [], confidence: 0.88, reason: 'Coinciden senales.' },
          detectedContext: {
            project: 'Pulse Hub',
            team: 'Producto',
            meetingObjective: ['validar avances del sprint', 'destrabar QA'],
            relevantSignals: ['lenguaje:seguimiento', 'estructura:bloqueos'],
          },
          analysisStrategy: {
            strategyId: 'delivery_weekly_sync',
            strategyName: 'Delivery Weekly Sync',
            whyThisStrategy: 'La estrategia prioriza acuerdos, bloqueos y siguientes pasos.',
            extractionFocus: ['acuerdos', 'bloqueos', 'siguientes pasos'],
          },
          executiveSummary: 'Se revisaron avances del sprint, bloqueos de QA y acuerdos para cerrar pendientes hoy.',
          keyPoints: [],
          decisions: [],
          agreements: [],
          tasks: [],
          risks: [],
          openQuestions: [],
          unresolvedItems: [],
          followUpRecommendation: {
            suggested: true,
            type: 'validation',
            description: 'Validar cierre de pendientes al final del dia.',
            confidence: 0.72,
            reason: 'Hay tareas abiertas que requieren confirmacion.',
          },
          destinationRecommendation: { suggestedDestination: 'Project Hub', confidence: 0.8, reason: 'Impacta el seguimiento operativo.' },
          messageDrafts: [],
          governance: { autonomyLevelApplied: 2, sensitiveActionsBlocked: [], requiresHumanApproval: true, explanationVisible: true },
        },
      },
    },
    sync_actions: [],
    approvals: [],
  };
}
