import type { MouseEvent } from 'react';
import type { Conversation } from '../../services/chat-service';
import type { Folder } from '../../services/folder-service';
import type { IrisIssue, IrisProject, IrisTeam } from '../../lib/iris-client';
import type { ThemeMode } from '../../hooks/useTheme';

export interface SidebarProps {
  isOpen: boolean;
  onToggle: () => void;
  activeView: string;
  conversations: Conversation[];
  currentConversationId: string | null;
  loadingConversations: boolean;
  onNewChat: () => void;
  onSelectConversation: (id: string) => void;
  onDeleteConversation: (id: string, e: MouseEvent) => void;
  renamingChatId: string | null;
  onSetRenamingChatId: (id: string | null) => void;
  editingChatTitle: string;
  onSetEditingChatTitle: (title: string) => void;
  onRenameChat: () => void;
  activeMenuChatId: string | null;
  onSetActiveMenuChatId: (id: string | null) => void;
  onSetMovingChatId: (id: string | null) => void;
  folders: Folder[];
  expandedFolders: Set<string>;
  currentFolderId: string | null;
  onCreateFolderClick: () => void;
  onToggleFolder: (id: string) => void;
  onOpenProject: (id: string) => void;
  onDeleteFolder: (id: string, e: MouseEvent) => void;
  irisTeams: IrisTeam[];
  irisProjects: IrisProject[];
  irisIssues: Record<string, IrisIssue[]>;
  expandedTeams: Set<string>;
  expandedProjects: Set<string>;
  onToggleTeam: (id: string) => void;
  onToggleProject: (id: string) => void;
  onIrisProjectClick: (project: IrisProject) => void;
  onIrisIssueClick: (issue: IrisIssue) => void;
  onRefreshIris: () => void;
  displayName: string;
  initials: string;
  userEmail: string | undefined;
  avatarUrl: string | undefined;
  orgLogoUrl: string | undefined;
  theme: ThemeMode;
  onSetTheme: (t: ThemeMode) => void;
  onOpenSettings: () => void;
  onSignOut: () => void;
}
