import { booleanProp, emptyParams, numberProp, objectParams, stringArrayProp, stringProp } from './schema';
import type { GeminiFunctionDeclaration } from './types';

export const GMAIL_TOOL_DECLARATIONS: GeminiFunctionDeclaration[] = [
  { name: 'gmail_get_messages', description: 'Obtiene mensajes de Gmail con filtros, etiquetas y paginacion.', parameters: objectParams({ query: stringProp('Filtro de busqueda de Gmail. Opcional.'), max_results: numberProp('Numero maximo de mensajes a obtener.'), label_ids: stringArrayProp('IDs de etiquetas para filtrar mensajes. Opcional.'), page_token: stringProp('Cursor devuelto por una llamada anterior para continuar la paginacion. Opcional.') }) },
  { name: 'gmail_read_message', description: 'Lee el contenido completo de un mensaje de Gmail por su ID.', parameters: objectParams({ message_id: stringProp('ID del mensaje de Gmail.') }, ['message_id']) },
  { name: 'gmail_send', description: 'Envia un correo desde la cuenta de Gmail conectada del usuario.', parameters: objectParams({ to: stringProp('Correo del destinatario.'), subject: stringProp('Asunto del correo.'), body: stringProp('Cuerpo del correo.'), is_html: booleanProp('Si es true, interpreta el body como HTML.'), attachment_paths: stringArrayProp('Rutas locales de archivos a adjuntar. Opcional.') }, ['to', 'subject', 'body']) },
  { name: 'gmail_get_labels', description: 'Lista las etiquetas de Gmail disponibles.', parameters: emptyParams() },
  { name: 'gmail_create_label', description: 'Crea una nueva etiqueta de Gmail.', parameters: objectParams({ name: stringProp('Nombre de la etiqueta.') }, ['name']) },
  { name: 'gmail_delete_label', description: 'Elimina una etiqueta de Gmail por su ID.', parameters: objectParams({ label_id: stringProp('ID de la etiqueta.') }, ['label_id']) },
  { name: 'gmail_preview_organization', description: 'Analiza el inbox de Gmail y genera un plan determinista de organizacion por remitente o empresa sin modificar correos todavia.', parameters: objectParams({ query: stringProp('Filtro opcional de Gmail. Por defecto usa in:inbox.'), max_messages: numberProp('Maximo de correos a analizar para el preview.'), min_group_size: numberProp('Tamano minimo de grupo para proponer una etiqueta.'), remove_from_inbox: booleanProp('Si es true, el plan propondra sacar los correos del inbox al aplicar.'), page_limit: numberProp('Numero maximo de paginas de Gmail a recorrer en el preview.') }) },
  { name: 'gmail_apply_organization_plan', description: 'Aplica un plan de organizacion de Gmail generado previamente por gmail_preview_organization.', parameters: objectParams({ plan_id: stringProp('ID del plan generado en el preview.'), remove_from_inbox: booleanProp('Opcional. Sobrescribe si al aplicar se quitan los correos del inbox.') }, ['plan_id']) },
  { name: 'gmail_undo_organization_plan', description: 'Revierte un plan de organizacion de Gmail previamente aplicado. Si no se envia plan_id, intenta revertir el ultimo plan aplicado.', parameters: objectParams({ plan_id: stringProp('Opcional. ID del plan aplicado que se quiere revertir. Si se omite, usa el ultimo plan aplicado.') }) },
  { name: 'gmail_modify_labels', description: 'Agrega o quita etiquetas de un correo individual.', parameters: objectParams({ message_id: stringProp('ID del correo.'), add_labels: stringArrayProp('Etiquetas o IDs a agregar.'), remove_labels: stringArrayProp('Etiquetas o IDs a quitar.') }, ['message_id']) },
  { name: 'gmail_batch_empty_label', description: 'Vacia una etiqueta completa de Gmail y opcionalmente la elimina.', parameters: objectParams({ label_id: stringProp('ID de la etiqueta.'), delete_label: booleanProp('Si es true, elimina la etiqueta despues.') }, ['label_id']) },
  { name: 'gmail_empty_all_labels', description: 'Vacia y elimina todas las etiquetas creadas por el usuario en Gmail.', parameters: emptyParams() },
];
