import { booleanProp, emptyParams, numberProp, objectParams, stringProp } from './schema';
import type { GeminiFunctionDeclaration } from './types';

export const REMOTE_NODE_TOOL_DECLARATIONS: GeminiFunctionDeclaration[] = [
  { name: 'get_remote_node_host_status', description: 'Obtiene el estado del host de nodo remoto local.', parameters: emptyParams() },
  { name: 'configure_remote_node_host', description: 'Configura el host remoto local de Pulse.', parameters: objectParams({ enabled: booleanProp('Activa o desactiva el host remoto.'), bind_address: stringProp('Direccion de escucha.'), port: numberProp('Puerto TCP.'), node_name: stringProp('Nombre legible del nodo.'), advertise_url: stringProp('URL publica opcional.'), rotate_token: booleanProp('Si es true, regenera el token.') }) },
  { name: 'list_remote_nodes', description: 'Lista los nodos remotos registrados.', parameters: emptyParams() },
  { name: 'register_remote_node', description: 'Registra o actualiza un nodo remoto.', parameters: objectParams({ node_id: stringProp('ID opcional del nodo.'), name: stringProp('Nombre del nodo remoto.'), base_url: stringProp('URL base del nodo remoto.'), token: stringProp('Token del nodo remoto.'), enabled: booleanProp('Si es false, queda deshabilitado.') }, ['name', 'base_url', 'token']) },
  { name: 'remove_remote_node', description: 'Elimina un nodo remoto registrado.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.') }, ['node_id']) },
  { name: 'test_remote_node', description: 'Prueba conectividad y capacidades de un nodo remoto.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.') }, ['node_id']) },
  { name: 'open_application_on_node', description: 'Abre una aplicacion en un nodo remoto.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.'), path: stringProp('Ruta o nombre de la aplicacion.') }, ['node_id', 'path']) },
  { name: 'run_background_command_on_node', description: 'Ejecuta un comando en segundo plano en un nodo remoto.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.'), command: stringProp('Comando a ejecutar.'), working_directory: stringProp('Directorio de trabajo opcional.'), title: stringProp('Etiqueta de la sesion.') }, ['node_id', 'command']) },
  { name: 'take_screenshot_on_node', description: 'Captura la pantalla actual de un nodo remoto.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.'), display_id: stringProp('Display especifico opcional.') }, ['node_id']) },
  { name: 'use_computer_on_node', description: 'Ejecuta una tarea de automation en un nodo remoto.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.'), task: stringProp('Descripcion detallada de la tarea.'), max_steps: numberProp('Maximo de pasos.'), backend: stringProp('Opcional: auto, browser, uia o desktop.'), start_url: stringProp('URL inicial opcional.'), browser_profile: stringProp('Perfil persistente opcional del browser remoto.'), browser_isolated: booleanProp('Si es true, fuerza sesion web aislada remota.'), reset_browser_profile: booleanProp('Si es true, limpia el perfil remoto antes de ejecutar.') }, ['node_id', 'task']) },
  { name: 'list_remote_node_process_sessions', description: 'Lista sesiones administradas de un nodo remoto.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.') }, ['node_id']) },
  { name: 'poll_remote_node_process_session', description: 'Consulta una sesion remota por session_id.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.'), session_id: stringProp('ID de la sesion remota.') }, ['node_id', 'session_id']) },
  { name: 'kill_remote_node_process_session', description: 'Termina una sesion remota.', parameters: objectParams({ node_id: stringProp('ID del nodo remoto.'), session_id: stringProp('ID de la sesion remota.') }, ['node_id', 'session_id']) },
];
