export const TOOL_DISPLAY_NAMES: Record<string, string> = {
  web_research: 'Investigando en la web...',
  research_actions: 'Preparando entregables...',
  create_word_document: 'Creando documento Word...',
  list_directory: 'Listando archivos...',
  read_file: 'Leyendo archivo...',
  write_file: 'Escribiendo archivo...',
  create_directory: 'Creando carpeta...',
  move_item: 'Moviendo...',
  copy_item: 'Copiando...',
  delete_item: 'Eliminando...',
  get_file_info: 'Obteniendo info...',
  search_files: 'Buscando archivos...',
  execute_command: 'Ejecutando comando...',
  open_application: 'Abriendo aplicación...',
  open_url: 'Abriendo URL...',
  get_system_info: 'Info del sistema...',
  clipboard_read: 'Leyendo portapapeles...',
  clipboard_write: 'Copiando al portapapeles...',
  take_screenshot: 'Capturando pantalla...',
  use_computer: 'Usando computadora...',
  get_email_config: 'Verificando email...',
  configure_email: 'Configurando email...',
  send_email: 'Enviando email...',
};
