-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.activity_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid,
  user_id uuid NOT NULL,
  timestamp timestamp with time zone NOT NULL DEFAULT now(),
  window_title text NOT NULL,
  process_name text NOT NULL,
  url text,
  category text DEFAULT 'uncategorized'::text,
  duration_seconds integer DEFAULT 30,
  idle boolean DEFAULT false,
  idle_seconds integer DEFAULT 0,
  ocr_text text,
  metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT activity_logs_pkey PRIMARY KEY (id),
  CONSTRAINT activity_logs_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.monitoring_sessions(id)
);
CREATE TABLE public.api_keys (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['google'::text, 'openai'::text])),
  api_key text NOT NULL,
  is_system_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.calendar_connections (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL,
  email text,
  access_token text NOT NULL,
  refresh_token text NOT NULL,
  token_expiry timestamp with time zone,
  calendar_id text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT calendar_connections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.conversation_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  shared_with_user_id uuid,
  org_id uuid NOT NULL,
  permission text NOT NULL DEFAULT 'view'::text CHECK (permission = ANY (ARRAY['view'::text, 'edit'::text])),
  share_token text UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT conversation_shares_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_shares_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);
CREATE TABLE public.conversations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  title text DEFAULT 'Nueva conversación'::text,
  mode text DEFAULT 'chat'::text,
  is_pinned boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  folder_id uuid,
  org_id uuid,
  CONSTRAINT conversations_pkey PRIMARY KEY (id),
  CONSTRAINT conversations_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT conversations_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.folders(id)
);
CREATE TABLE public.crm_companies (
  company_id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  name text NOT NULL,
  domain text,
  industry text,
  size_range text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_companies_pkey PRIMARY KEY (company_id)
);
CREATE TABLE public.crm_contacts (
  contact_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  organization_id uuid,
  full_name text NOT NULL,
  email text,
  phone text,
  role_title text,
  linkedin_url text,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_contacts_pkey PRIMARY KEY (contact_id),
  CONSTRAINT crm_contacts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.crm_companies(company_id)
);
CREATE TABLE public.crm_interactions (
  interaction_id uuid NOT NULL DEFAULT gen_random_uuid(),
  opportunity_id uuid,
  contact_id uuid,
  organization_id uuid,
  interaction_type text NOT NULL,
  channel text,
  raw_input text,
  ai_summary text,
  extracted_data jsonb DEFAULT '{}'::jsonb,
  trace_id uuid NOT NULL,
  source_ref text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_interactions_pkey PRIMARY KEY (interaction_id),
  CONSTRAINT crm_interactions_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.crm_opportunities(opportunity_id),
  CONSTRAINT crm_interactions_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.crm_contacts(contact_id)
);
CREATE TABLE public.crm_opportunities (
  opportunity_id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid,
  contact_id uuid,
  organization_id uuid,
  title text NOT NULL,
  stage text NOT NULL DEFAULT 'lead'::text,
  estimated_value numeric,
  currency text DEFAULT 'MXN'::text,
  close_date date,
  pains ARRAY,
  objections ARRAY,
  next_step text,
  owner_id uuid,
  lost_reason text,
  won_reason text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT crm_opportunities_pkey PRIMARY KEY (opportunity_id),
  CONSTRAINT crm_opportunities_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.crm_companies(company_id),
  CONSTRAINT crm_opportunities_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES public.crm_contacts(contact_id)
);
CREATE TABLE public.daily_summaries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  date date NOT NULL,
  total_time_seconds integer DEFAULT 0,
  productive_time_seconds integer DEFAULT 0,
  idle_time_seconds integer DEFAULT 0,
  top_apps jsonb DEFAULT '[]'::jsonb,
  top_websites jsonb DEFAULT '[]'::jsonb,
  ai_summary text,
  projects_detected jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT daily_summaries_pkey PRIMARY KEY (id)
);
CREATE TABLE public.folder_shares (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid NOT NULL,
  shared_by uuid NOT NULL,
  shared_with_user_id uuid,
  org_id uuid NOT NULL,
  permission text NOT NULL DEFAULT 'view'::text CHECK (permission = ANY (ARRAY['view'::text, 'edit'::text])),
  share_token text UNIQUE,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  revoked_at timestamp with time zone,
  CONSTRAINT folder_shares_pkey PRIMARY KEY (id),
  CONSTRAINT folder_shares_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.folders(id)
);
CREATE TABLE public.folders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  org_id uuid,
  CONSTRAINT folders_pkey PRIMARY KEY (id),
  CONSTRAINT folders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.meeting_action_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  description text NOT NULL,
  assignee text,
  due_date date,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'in_progress'::text, 'completed'::text])),
  source_segment_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_action_items_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_action_items_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.meeting_sessions(id),
  CONSTRAINT meeting_action_items_source_segment_id_fkey FOREIGN KEY (source_segment_id) REFERENCES public.transcript_segments(id)
);
CREATE TABLE public.meeting_exports (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  export_type text DEFAULT 'pdf'::text CHECK (export_type = ANY (ARRAY['pdf'::text, 'txt'::text, 'docx'::text])),
  include_transcript boolean DEFAULT true,
  include_summary boolean DEFAULT true,
  include_action_items boolean DEFAULT true,
  file_url text,
  file_size_bytes integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_exports_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_exports_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.meeting_sessions(id)
);
CREATE TABLE public.meeting_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['google-meet'::text, 'zoom'::text])),
  title text,
  meeting_url text,
  start_time timestamp with time zone NOT NULL DEFAULT now(),
  end_time timestamp with time zone,
  duration_seconds integer,
  participants jsonb DEFAULT '[]'::jsonb,
  participant_count integer DEFAULT 1,
  summary text,
  summary_type text CHECK (summary_type = ANY (ARRAY['short'::text, 'detailed'::text, 'action_items'::text, 'executive'::text])),
  detected_language text DEFAULT 'es'::text CHECK (detected_language = ANY (ARRAY['es'::text, 'en'::text, 'pt'::text])),
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT meeting_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT meeting_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.message_feedback (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  message_content text,
  model_used text,
  rating integer,
  feedback_type text,
  reason_category text,
  feedback_text text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT message_feedback_pkey PRIMARY KEY (id),
  CONSTRAINT message_feedback_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  conversation_id uuid NOT NULL,
  user_id uuid NOT NULL,
  role text NOT NULL CHECK (role = ANY (ARRAY['user'::text, 'model'::text])),
  content text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT messages_pkey PRIMARY KEY (id),
  CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id),
  CONSTRAINT messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.monitoring_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  ended_at timestamp with time zone,
  trigger_type text NOT NULL DEFAULT 'manual'::text,
  calendar_event_title text,
  total_active_seconds integer DEFAULT 0,
  total_idle_seconds integer DEFAULT 0,
  summary_text text,
  status text NOT NULL DEFAULT 'active'::text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT monitoring_sessions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  email text,
  full_name text,
  avatar_url text,
  plan_type text DEFAULT 'free'::text,
  created_at timestamp with time zone DEFAULT now(),
  first_name text,
  last_name_p text,
  last_name_m text,
  phone text,
  nationality text,
  username text UNIQUE,
  preferred_primary_model text DEFAULT 'gemini-2.0-flash'::text,
  preferred_fallback_model text DEFAULT 'gemini-1.5-flash'::text,
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.tools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  author_id uuid,
  name text NOT NULL,
  description text NOT NULL,
  icon text DEFAULT '🔧'::text,
  category USER-DEFINED NOT NULL,
  system_prompt text NOT NULL,
  starter_prompts jsonb DEFAULT '[]'::jsonb,
  status USER-DEFINED DEFAULT 'pending'::tool_status,
  reviewed_by uuid,
  reviewed_at timestamp with time zone,
  rejection_reason text,
  usage_count integer DEFAULT 0,
  is_featured boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tools_pkey PRIMARY KEY (id),
  CONSTRAINT tools_author_id_fkey FOREIGN KEY (author_id) REFERENCES auth.users(id),
  CONSTRAINT tools_reviewed_by_fkey FOREIGN KEY (reviewed_by) REFERENCES auth.users(id)
);
CREATE TABLE public.transcript_segments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  timestamp timestamp with time zone NOT NULL,
  relative_time_ms integer,
  speaker text,
  text text NOT NULL,
  is_lia_response boolean DEFAULT false,
  is_lia_invocation boolean DEFAULT false,
  language text DEFAULT 'es'::text,
  confidence double precision,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT transcript_segments_pkey PRIMARY KEY (id),
  CONSTRAINT transcript_segments_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.meeting_sessions(id)
);
CREATE TABLE public.user_ai_settings (
  user_id uuid NOT NULL,
  primary_model text NOT NULL DEFAULT 'gemini-2.0-flash'::text,
  fallback_model text NOT NULL DEFAULT 'gemini-1.5-flash'::text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  nickname text,
  occupation text,
  about_user text,
  tone_style text DEFAULT 'Profesional'::text,
  char_emojis text DEFAULT 'Auto'::text,
  custom_instructions text,
  thinking_mode text DEFAULT 'minimal'::text,
  CONSTRAINT user_ai_settings_pkey PRIMARY KEY (user_id),
  CONSTRAINT user_ai_settings_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.user_favorite_tools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  tool_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_favorite_tools_pkey PRIMARY KEY (id),
  CONSTRAINT user_favorite_tools_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT user_favorite_tools_tool_id_fkey FOREIGN KEY (tool_id) REFERENCES public.tools(id)
);
CREATE TABLE public.user_tools (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text,
  icon text DEFAULT '⚙️'::text,
  category USER-DEFINED,
  system_prompt text NOT NULL,
  starter_prompts jsonb DEFAULT '[]'::jsonb,
  is_favorite boolean DEFAULT false,
  usage_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_tools_pkey PRIMARY KEY (id),
  CONSTRAINT user_tools_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.workflow_approvals (
  approval_id uuid NOT NULL DEFAULT gen_random_uuid(),
  artifact_id uuid,
  step_run_id uuid,
  run_id uuid,
  trace_id uuid NOT NULL,
  decision text NOT NULL,
  reason text,
  approved_by uuid NOT NULL,
  role_at_time text,
  evidence_links ARRAY,
  artifact_version_before integer,
  artifact_version_after integer,
  idempotency_key text UNIQUE,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_approvals_pkey PRIMARY KEY (approval_id),
  CONSTRAINT workflow_approvals_artifact_id_fkey FOREIGN KEY (artifact_id) REFERENCES public.workflow_artifacts(artifact_id),
  CONSTRAINT workflow_approvals_step_run_id_fkey FOREIGN KEY (step_run_id) REFERENCES public.workflow_step_runs(step_run_id),
  CONSTRAINT workflow_approvals_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.workflow_runs(run_id)
);
CREATE TABLE public.workflow_artifacts (
  artifact_id uuid NOT NULL DEFAULT gen_random_uuid(),
  step_run_id uuid,
  run_id uuid,
  trace_id uuid NOT NULL,
  artifact_type text NOT NULL,
  version integer NOT NULL DEFAULT 1,
  ai_output_raw text,
  human_edit text,
  human_final text,
  human_edit_diff jsonb,
  prompt_hash text,
  model_used text,
  qa_result jsonb,
  status text NOT NULL DEFAULT 'draft'::text,
  created_by uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_artifacts_pkey PRIMARY KEY (artifact_id),
  CONSTRAINT workflow_artifacts_step_run_id_fkey FOREIGN KEY (step_run_id) REFERENCES public.workflow_step_runs(step_run_id),
  CONSTRAINT workflow_artifacts_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.workflow_runs(run_id)
);
CREATE TABLE public.workflow_definitions (
  definition_id uuid NOT NULL DEFAULT gen_random_uuid(),
  organization_id uuid,
  slug text NOT NULL UNIQUE,
  name text NOT NULL,
  description text,
  steps_config jsonb NOT NULL,
  is_active boolean DEFAULT true,
  version integer DEFAULT 1,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_definitions_pkey PRIMARY KEY (definition_id)
);
CREATE TABLE public.workflow_runs (
  run_id uuid NOT NULL DEFAULT gen_random_uuid(),
  definition_id uuid,
  organization_id uuid,
  trace_id uuid NOT NULL UNIQUE,
  trigger_type text NOT NULL,
  trigger_ref text,
  current_step_key text NOT NULL,
  status text NOT NULL DEFAULT 'active'::text,
  context_data jsonb DEFAULT '{}'::jsonb,
  opportunity_id uuid,
  owner_id uuid NOT NULL,
  started_at timestamp with time zone DEFAULT now(),
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_runs_pkey PRIMARY KEY (run_id),
  CONSTRAINT workflow_runs_definition_id_fkey FOREIGN KEY (definition_id) REFERENCES public.workflow_definitions(definition_id),
  CONSTRAINT workflow_runs_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES public.crm_opportunities(opportunity_id)
);
CREATE TABLE public.workflow_step_runs (
  step_run_id uuid NOT NULL DEFAULT gen_random_uuid(),
  run_id uuid,
  step_key text NOT NULL,
  status text NOT NULL DEFAULT 'pending'::text,
  assigned_to uuid,
  sla_due_at timestamp with time zone,
  escalated_at timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workflow_step_runs_pkey PRIMARY KEY (step_run_id),
  CONSTRAINT workflow_step_runs_run_id_fkey FOREIGN KEY (run_id) REFERENCES public.workflow_runs(run_id)
);
CREATE TABLE public.workspace_sources (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  folder_id uuid,
  conversation_id uuid,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['drive'::text, 'outlook'::text, 'upload'::text])),
  file_name text NOT NULL,
  file_size bigint,
  mime_type text,
  external_file_id text,
  external_url text,
  storage_path text,
  added_by uuid NOT NULL,
  org_id uuid NOT NULL,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT workspace_sources_pkey PRIMARY KEY (id),
  CONSTRAINT workspace_sources_folder_id_fkey FOREIGN KEY (folder_id) REFERENCES public.folders(id),
  CONSTRAINT workspace_sources_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES public.conversations(id)
);